version: '3.8'

services:
  # Jenkins personnalisé avec Node.js
  jenkins-custom:
    build: 
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-calculatrice
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    networks:
      - jenkins-network

  # Application calculatrice
  calculatrice-app:
    build: .
    container_name: calculatrice-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./public:/app/public:ro
    restart: unless-stopped
    networks:
      - jenkins-network
    depends_on:
      - jenkins-custom

volumes:
  jenkins_data:
    driver: local

networks:
  jenkins-network:
    driver: bridge
